name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Perform search and replace
        run: |
          sed -i 's/APIKEY/'"${{ secrets.APIKEY }}"'/' js/main.js
          sed -i 's/SPREADSHEETID/'"${{ secrets.SPREADSHEETID }}"'/' js/main.js

      - name: Display modified main.js content
        run: |
          cat js/main.js

      - name: Commit and push changes
        run: |
          git add js/main.js
          git commit -m "Update main.js with replaced values"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
