name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Perform search and replace
        run: |
          sed -i 's/APIKEY/'"${{ secrets.APIKEY }}"'/' js/main.js
          sed -i 's/SPREADSHEETID/'"${{ secrets.SPREADSHEETID }}"'/' js/main.js

      - name: Display modified main.js content
        run: |
          cat js/main.js
          
      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install

      - name: Fetch data
        run: |
          node -e '
          var apiKey = process.env.API_KEY || "APIKEY";
          var spreadsheetId = process.env.SPREADSHEET_ID || "SPREADSHEETID";
          var sheetUrl = `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}?includeGridData=true&key=${apiKey}`;
          // Add your data fetching logic here using sheetUrl
          '
          
      - name: Commit and push updated data
        run: |
          git config --global user.name "timmit147"
          git config --global user.email "timmeeuwsen@hotmail.nl"
          git add .
          git commit -m "Update data"
          git push
