name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      issues: write
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Perform search and replace
        run: |
          sed -i 's/APIKEY/'"${{ secrets.APIKEY }}"'/' js/main.js
          sed -i 's/SPREADSHEETID/'"${{ secrets.SPREADSHEETID }}"'/' js/main.js

      - name: Display modified main.js content
        run: |
          cat js/main.js
      - name: Commit and push changes
        run: |
          git config --global user.name "timmit147"
          git config --global user.email "timmeeuwsen@hotmail.nl"
          git add js/json.js
          git commit -m "Update json.js with replaced values"
          git push
