name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use the secret
        env:
          APIKEY: ${{ secrets.APIKEY }}
          SPREADSHEETID: ${{ secrets.SPREADSHEETID }}
        run: |
          sed -i "s/APIKEY/$APIKEY/" js/main.js
          sed -i "s/SPREADSHEETID/$SPREADSHEETID/" js/main.js
          cat js/main.js  # Optional: Print the updated content of the file
          # Use the updated file in further steps or commands
