name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Perform search and replace
        run: |
          sed -i 's/API_KEY/'"${{ secrets.APIKEY }}"'/' js/main.js
          sed -i 's/SPREADSHEET_ID/'"${{ secrets.SPREADSHEETID }}"'/' js/main.js

      - name: Display modified main.js content
        run: |
          cat js/main.js
