name: Fetch Data

on:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch data
        run: |
          # Your data fetching script/command goes here
          # For example, using cURL to fetch data from an API
          curl -o data.json https://api.example.com/data

      - name: Commit and push updated data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update data.json"
          git push
