name: Fetch Google Sheets Data

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  fetchJob:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run script
        run: |
          npm install node-fetch
          node -e "
            const fetch = require('node-fetch');

            function fetchSheetAsJSON() {
              var apiKey = process.env.API_KEY || 'APIKEY';
              var spreadsheetId = process.env.SPREADSHEET_ID || 'SPREADSHEETID';
              var sheetUrl = `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}?includeGridData=true&key=${apiKey}`;

              return fetch(sheetUrl)
                .then(function(response) {
                  if (!response.ok) {
                    throw new Error('Failed to fetch Google Sheets data');
                  }
                  return response.json();
                });
            }

            fetchSheetAsJSON()
              .then(function(data) {
                console.log(data);
              })
              .catch(function(error) {
                console.error('Error fetching Google Sheets data:', error);
              });
          "
