name: Text Replace and Push

on:
  push:
    branches:
      - main # Change this to the desired branch name

jobs:
  text_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # ... other steps ...

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "timmit147"
        git config --global user.email "timmeeuwsen@hotmail.nl"
        git add js/json.js
        git commit -m "Update js/json.js with replaced values"
        git push origin main
