name: Update File Content

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs: 
  update_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch origin main  # Replace 'main' with the appropriate branch name

      - name: Create new branch
        run: git checkout -b update-file-content

      - name: Set git user email and name
        run: |
          git config --local user.email "timmeeuwsen@hotmail.nl" 
          git config --local user.name "timmit147"
      
      - name: Modify file content
        run: |
          # File to be updated
          FILE_PATH="js/json.js"

          # New content for the file
          NEW_CONTENT="console.log('Hello, World!');"

          # Replace the content in the file
          echo "$NEW_CONTENT" > "$FILE_PATH"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update file content"

      - name: Push changes to the new branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git push origin update-file-content

      - name: Create pull request
        run: |
          gh pr create --base main --head update-file-content --title "Update File Content" --body "This pull request updates the content of the js/json.js file."
