name: Text Replace and Push

on:
  push:
    branches:
      - main # Change this to the desired branch name

jobs:
  text_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine version number
      id: version
      run: |
        version=$(grep -oP '^\/\/ Version \K(\d+)' js/json.js)
        if [ -z "$version" ]; then
          version=1
        else
          version=$((version + 1))
        fi
        echo "Version $version" >> js/json.js
        echo "::set-output name=version::$version"

    - name: Replace text in main.js
      run: |
        sed -i 's/jsonReplace/hello/g' js/json.js

    - name: Commit changes
      run: |
        git config --local user.email "timmeeuwsen@hotmail.nl"
        git config --local user.name "timmit147"
        git commit -am "Text replace using GitHub Action (Version ${{ steps.version.outputs.version }})"
        git push
