name: Update File with Fetched JSON

on:
  repository_dispatch:
    types: update_sheets_data

jobs:
  update_file_with_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch JSON data
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEETID }}
          API_KEY: ${{ secrets.APIKEY }}
        run: |
          # Add a timestamp as a cache-busting query parameter
          TIMESTAMP=$(date +%s)
          curl -s -o fetchedData.json "https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}?includeGridData=true&key=${API_KEY}&timestamp=${TIMESTAMP}"
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x' # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install # You can use yarn if you prefer

      - name: Update File
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Remove the timestamp from the file
          cat fetchedData.json > js/json.js
          # Commit and push the changes back to the repository
          git config --global user.name "timmit147"
          git config --global user.email "timmeeuwsen@hotmail.nl"
          git add js/json.js
          git commit -m "Update file with fetched JSON data"
          git push origin main
