name: Text Replace and Push

on:
  push:
    branches:
      - main # Change this to the desired branch name

jobs:
  text_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # ... other steps ...

    - name: Replace text in js/json.js
      run: |
        sed -i 's/jsonReplace/hello/g' js/json.js

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update js/json.js with replaced values"
        commit_options: "--author 'timmit147 <timmeeuwsen@hotmail.nl>'"
