name: Text Replace and Push

on:
  push:
    branches:
      - main # Change this to the desired branch name

jobs:
  text_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the directory (for debugging purposes)
      run: |
        ls -la js/

    - name: Check if version exists and set to 1 if not
      id: version
      run: |
        if ! grep -q '^\/\/ Version' js/json.js; then
          echo -e "// Version 1\n$(cat js/json.js)" > js/json.js
          version=1
        else
          version=$(grep -oP '^\/\/ Version \K(\d+)' js/json.js)
        fi
        echo "::set-output name=version::$version"

    - name: Replace text in js/json.js
      run: |
        sed -i 's/jsonReplace/hello/g' js/json.js

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update js/json.js with replaced values"
        commit_user_name: "timmit147" # Set the correct author name here
        commit_user_email: "timmeeuwsen@hotmail.nl" # Set the correct author email here
