name: Text Replace and Push

on:
  push:
    branches:
      - main # Change this to the desired branch name

jobs:
  text_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace text in main.js
      run: |
        # Replace "jsonReplace" with "hello" in main.js
        sed -i 's/jsonReplace/hello/g' main.js

    - name: Commit changes
      run: |
        git config --local user.email "timmeeuwsen@hotmail.nl"
        git config --local user.name "timmit147"
        git commit -am "Text replace using GitHub Action"
        git push
