name: Update File Content

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  update_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch origin main  # Replace 'main' with the appropriate branch name

      - name: Reset to latest commit
        run: git reset --hard origin/main

      - name: Update file content
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Set your username and email
          USERNAME="timmit147"
          EMAIL="timmeeuwsen@hotmail.nl"
          
          # File to be updated
          FILE_PATH="js/json.js"

          # New content for the file
          NEW_CONTENT="console.log('Hello, World!');"

          # Base64 encode the new content
          ENCODED_CONTENT=$(echo "$NEW_CONTENT" | base64)

          # Get the current commit SHA
          COMMIT_SHA=$(git rev-parse HEAD)

          # Update the file using the GitHub API
          curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"Update file content\", \"committer\": {\"name\": \"$USERNAME\", \"email\": \"$EMAIL\"}, \"content\": \"$ENCODED_CONTENT\", \"sha\": \"$COMMIT_SHA\"}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/contents/$FILE_PATH"
